// @vitest-environment node
import { randomUUID } from "node:crypto";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
const run = `product_${randomUUID().replaceAll("-", "")}`; let db: typeof import("@/lib/db").db; let saveProduct: typeof import("@/lib/catalog/admin-mutations").saveProduct;
const draft = (suffix:string) => ({ name:`Bottes ${suffix}`,description:"Description de produit de test isolée.",priceDh:700,slug:`${run}-${suffix}`,isVisible:false,images:[],variants:[] });
async function cleanup(){await db.order.deleteMany({where:{items:{some:{variant:{product:{slug:{startsWith:run}}}}}}});await db.product.deleteMany({where:{slug:{startsWith:run}}});}
beforeAll(async()=>{const raw=process.env.TEST_DATABASE_URL;if(!raw)throw new Error("Integration precondition: set exclusive TEST_DATABASE_URL with a database name containing test.");const url=new URL(raw);if(!/^postgres(?:ql)?:$/.test(url.protocol)||!/test/i.test(decodeURIComponent(url.pathname.slice(1))))throw new Error("Refusing non-test PostgreSQL database.");process.env.DATABASE_URL=raw;({db}=await import("@/lib/db"));({saveProduct}=await import("@/lib/catalog/admin-mutations"));await cleanup()});
afterAll(async()=>{if(db){await cleanup();await db.$disconnect()}});
describe.sequential("saveProduct PostgreSQL integration",()=>{
 it("crée un brouillon puis publie avec image, déclinaison et stock",async()=>{const created=await saveProduct(draft("create"));const updated=await saveProduct({...draft("create"),id:created.id,isVisible:true,images:[{url:"https://example.com/a.webp",alt:"Botte test",position:0}],variants:[{sku:`${run}-SKU`,size:"38",color:"Noir",stock:9}]});expect(updated.id).toBe(created.id);await expect(db.product.findUniqueOrThrow({where:{id:created.id},include:{variants:true,images:true}})).resolves.toMatchObject({isVisible:true,variants:[{stock:9}],images:[{position:0}]})});
 it("retourne des conflits sûrs pour slug et SKU",async()=>{const one=await saveProduct(draft("unique-a"));await expect(saveProduct({...draft("unique-b"),slug:draft("unique-a").slug})).rejects.toMatchObject({code:"DUPLICATE_SLUG"});await saveProduct({...draft("unique-a"),id:one.id,variants:[{sku:`${run}-UNIQUE`,size:"39",color:"Brun",stock:1}]});await expect(saveProduct({...draft("unique-c"),variants:[{sku:`${run}-UNIQUE`,size:"40",color:"Noir",stock:2}]})).rejects.toMatchObject({code:"DUPLICATE_SKU"})});
 it("rejette une combinaison dupliquée avant écriture",async()=>{await expect(saveProduct({...draft("combo"),variants:[{sku:`${run}-C1`,size:"38",color:"Noir",stock:1},{sku:`${run}-C2`,size:"38",color:"Noir",stock:2}]})).rejects.toMatchObject({code:"INVALID"})});
 it("supprime l’omission sans historique mais conserve à stock zéro celle commandée",async()=>{const created=await saveProduct({...draft("history"),variants:[{sku:`${run}-H1`,size:"38",color:"Noir",stock:4},{sku:`${run}-H2`,size:"39",color:"Noir",stock:5}]});const variants=await db.productVariant.findMany({where:{productId:created.id},orderBy:{size:"asc"}});await db.order.create({data:{number:`BOT-${randomUUID().replaceAll("-","").slice(0,10).toUpperCase()}`,customerFirstName:"A",customerLastName:"B",customerPhone:"+212600000000",customerAddress:"Test",totalDh:700,items:{create:{variantId:variants[0].id,productName:"Bottes",size:"38",color:"Noir",unitPriceDh:700,quantity:1}}}});await saveProduct({...draft("history"),id:created.id,variants:[]});const left=await db.productVariant.findMany({where:{productId:created.id}});expect(left).toHaveLength(1);expect(left[0]).toMatchObject({id:variants[0].id,stock:0})});
 it("rejette un identifiant de déclinaison appartenant à un autre produit",async()=>{const a=await saveProduct({...draft("owner-a"),variants:[{sku:`${run}-OA`,size:"38",color:"Noir",stock:1}]});const b=await saveProduct(draft("owner-b"));const variant=await db.productVariant.findFirstOrThrow({where:{productId:a.id}});await expect(saveProduct({...draft("owner-b"),id:b.id,variants:[{id:variant.id,sku:`${run}-OB`,size:"39",color:"Brun",stock:2}]})).rejects.toMatchObject({code:"TAMPERED_VARIANT"})});
});
