// @vitest-environment node
import { randomUUID } from "node:crypto";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { isSafeTestDatabaseUrl } from "../support/test-database-url";
const run = `product_${randomUUID().replaceAll("-", "")}`; let db: typeof import("@/lib/db").db; let saveProduct: typeof import("@/lib/catalog/admin-mutations").saveProduct;
const draft = (suffix:string) => ({ name:`Bottes ${suffix}`,description:"Description de produit de test isolée.",priceDh:700,slug:`${run}-${suffix}`,isVisible:false,images:[],variants:[] });
async function cleanup(){await db.order.deleteMany({where:{items:{some:{variant:{product:{slug:{startsWith:run}}}}}}});await db.product.deleteMany({where:{slug:{startsWith:run}}});}
beforeAll(async()=>{const raw=process.env.TEST_DATABASE_URL;if(!raw)throw new Error("Integration precondition: set exclusive TEST_DATABASE_URL named test or ending in _test.");if(!isSafeTestDatabaseUrl(raw))throw new Error("Refusing non-test PostgreSQL database.");process.env.DATABASE_URL=raw;({db}=await import("@/lib/db"));({saveProduct}=await import("@/lib/catalog/admin-mutations"));await cleanup()});
afterAll(async()=>{if(db){await cleanup();await db.$disconnect()}});
describe.sequential("saveProduct PostgreSQL integration",()=>{
 it("crée un brouillon puis publie avec image, déclinaison et stock",async()=>{const created=await saveProduct(draft("create"));const updated=await saveProduct({...draft("create"),id:created.id,isVisible:true,images:[{url:"https://images.unsplash.com/a.webp",alt:"Botte test",color:"Noir",position:0}],variants:[{sku:`${run}-SKU`,size:"38",color:"Noir",stock:9}]});expect(updated.id).toBe(created.id);await expect(db.product.findUniqueOrThrow({where:{id:created.id},include:{variants:true,images:true}})).resolves.toMatchObject({isVisible:true,variants:[{stock:9}],images:[{position:0}]})});
 it("retourne des conflits sûrs pour slug et SKU",async()=>{const one=await saveProduct(draft("unique-a"));await expect(saveProduct({...draft("unique-b"),slug:draft("unique-a").slug})).rejects.toMatchObject({code:"DUPLICATE_SLUG"});await saveProduct({...draft("unique-a"),id:one.id,variants:[{sku:`${run}-UNIQUE`,size:"39",color:"Brun",stock:1}]});await expect(saveProduct({...draft("unique-c"),variants:[{sku:`${run}-UNIQUE`,size:"40",color:"Noir",stock:2}]})).rejects.toMatchObject({code:"DUPLICATE_SKU"})});
 it("rejette une combinaison dupliquée avant écriture",async()=>{await expect(saveProduct({...draft("combo"),variants:[{sku:`${run}-C1`,size:"38",color:"Noir",stock:1},{sku:`${run}-C2`,size:"38",color:"Noir",stock:2}]})).rejects.toMatchObject({code:"INVALID"})});
 it("supprime la déclinaison omise sans historique et préserve celle commandée avec son snapshot",async()=>{const created=await saveProduct({...draft("history"),images:[{url:"https://images.unsplash.com/history.webp",alt:"Botte noire de test",color:"Noir",position:0}],variants:[{sku:`${run}-H1`,size:"38",color:"Noir",stock:4},{sku:`${run}-H2`,size:"39",color:"Noir",stock:5}]});const variants=await db.productVariant.findMany({where:{productId:created.id},orderBy:{size:"asc"}});const ordered=variants[0];const neverOrdered=variants[1];const snapshot={productName:"Bottes au moment de la commande",size:ordered.size,color:ordered.color,unitPriceDh:650,quantity:2};const order=await db.order.create({data:{number:`BOT-${randomUUID().replaceAll("-","").slice(0,10).toUpperCase()}`,customerFirstName:"A",customerLastName:"B",customerPhone:"+212600000000",customerAddress:"Test",totalDh:1300,items:{create:{variantId:ordered.id,...snapshot}}},include:{items:true}});const orderItemId=order.items[0].id;await saveProduct({...draft("history"),id:created.id,images:[],variants:[]});await expect(db.productVariant.findUnique({where:{id:ordered.id}})).resolves.toMatchObject({id:ordered.id,stock:0});await expect(db.productVariant.findUnique({where:{id:neverOrdered.id}})).resolves.toBeNull();await expect(db.orderItem.findUnique({where:{id:orderItemId}})).resolves.toMatchObject({id:orderItemId,orderId:order.id,variantId:ordered.id,...snapshot})});
 it("rejette un identifiant de déclinaison appartenant à un autre produit",async()=>{const a=await saveProduct({...draft("owner-a"),variants:[{sku:`${run}-OA`,size:"38",color:"Noir",stock:1}]});const b=await saveProduct(draft("owner-b"));const variant=await db.productVariant.findFirstOrThrow({where:{productId:a.id}});await expect(saveProduct({...draft("owner-b"),id:b.id,variants:[{id:variant.id,sku:`${run}-OB`,size:"39",color:"Brun",stock:2}]})).rejects.toMatchObject({code:"TAMPERED_VARIANT"})});
 it("réconcilie les images éditées, leur ordre et les images omises",async()=>{const variants=[{sku:`${run}-IMAGES-SKU`,size:"38",color:"Noir",stock:1}];const created=await saveProduct({...draft("images"),images:[{url:"https://images.unsplash.com/first.webp",alt:"Première botte",color:"Noir",position:0},{url:"https://images.unsplash.com/second.webp",alt:"Deuxième botte",color:"Noir",position:1}],variants});const before=await db.productImage.findMany({where:{productId:created.id},orderBy:{position:"asc"}});await saveProduct({...draft("images"),id:created.id,images:[{id:before[1].id,url:before[1].url,alt:"Deuxième botte mise à jour",color:"Noir",position:0}],variants});const after=await db.productImage.findMany({where:{productId:created.id},orderBy:{position:"asc"}});expect(after).toHaveLength(1);expect(after[0]).toMatchObject({url:"https://images.unsplash.com/second.webp",alt:"Deuxième botte mise à jour",position:0});expect(after.some((image)=>image.url==="https://images.unsplash.com/first.webp")).toBe(false)});
 it("annule entièrement une édition si une contrainte tardive échoue",async()=>{await saveProduct({...draft("rollback-reserved"),variants:[{sku:`${run}-ROLLBACK-SKU`,size:"41",color:"Noir",stock:1}]});const created=await saveProduct({...draft("rollback"),images:[{url:"https://images.unsplash.com/original.webp",alt:"Image originale",color:"Marron",position:0}],variants:[{sku:`${run}-ROLLBACK-OWN`,size:"38",color:"Marron",stock:4}]});const before=await db.product.findUniqueOrThrow({where:{id:created.id},include:{images:{orderBy:{position:"asc"}},variants:{orderBy:{sku:"asc"}}}});await expect(saveProduct({...draft("rollback"),id:created.id,name:"Nom qui doit être annulé",images:[{url:"https://images.unsplash.com/replacement.webp",alt:"Image de remplacement",color:"Bleu",position:0}],variants:[{sku:`${run}-ROLLBACK-SKU`,size:"42",color:"Bleu",stock:9}]})).rejects.toMatchObject({code:"DUPLICATE_SKU"});const after=await db.product.findUniqueOrThrow({where:{id:created.id},include:{images:{orderBy:{position:"asc"}},variants:{orderBy:{sku:"asc"}}}});expect(after).toEqual(before)});
});
