"use client";
import { FormEvent, useRef, useState } from "react"; import { useRouter } from "next/navigation";
import { saveProductAction } from "@/app/actions/save-product"; import { uploadProductImageAction } from "@/app/actions/upload-product-image"; import { EditableVariant, VariantEditor } from "./variant-editor";
type EditableImage={id?:string;url:string;alt:string;position:number}; type Value={id?:string;name:string;description:string;priceDh:number;slug:string;isVisible:boolean;images:EditableImage[];variants:EditableVariant[]};
const empty:Value={name:"",description:"",priceDh:1,slug:"",isVisible:false,images:[],variants:[]};
export function ProductForm({initialValue}:{initialValue?:Value}) { const router=useRouter(); const [value,setValue]=useState(initialValue??empty); const [busy,setBusy]=useState(false); const [uploading,setUploading]=useState(false); const operationLock=useRef(false); const [message,setMessage]=useState(""); const [errors,setErrors]=useState<Record<string,string[]|undefined>>({}); const locked=busy||uploading; const canPublish=!!value.images.length&&!!value.variants.length;
 const move=(index:number,delta:number)=>{const target=index+delta;if(target<0||target>=value.images.length)return;const images=[...value.images];[images[index],images[target]]=[images[target],images[index]];setValue({...value,images:images.map((x,position)=>({...x,position}))})};
 async function upload(file?:File){if(!file||operationLock.current)return;operationLock.current=true;setUploading(true);setMessage("");const data=new FormData();data.set("file",file);try{const result=await uploadProductImageAction(data);if(result.ok)setValue(current=>({...current,images:[...current.images,{url:result.url,alt:current.name||"Image du produit",position:current.images.length}]}));else setMessage(result.message)}finally{operationLock.current=false;setUploading(false)}}
 async function submit(event:FormEvent){event.preventDefault();if(locked||operationLock.current)return;operationLock.current=true;setBusy(true);setMessage("");try{const result=await saveProductAction({...value,variants:value.variants.map((variant)=>({id:variant.id,sku:variant.sku,size:variant.size,color:variant.color,stock:variant.stock}))});if(!result.ok){setMessage(result.message);setErrors(result.fieldErrors);return}router.push(`/admin/produits/${result.id}`);router.refresh()}finally{operationLock.current=false;setBusy(false)}}
 return <form className="product-form" onSubmit={submit} aria-busy={locked}>{message&&<p role="alert" className="form-error-summary">{message}</p>}<label>Nom<input disabled={locked} required minLength={2} maxLength={120} value={value.name} onChange={e=>setValue({...value,name:e.target.value})}/></label>{errors.name&&<p className="field-error">{errors.name[0]}</p>}<label>Slug<input disabled={locked} required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" maxLength={120} value={value.slug} onChange={e=>setValue({...value,slug:e.target.value})}/></label>{errors.slug&&<p className="field-error">{errors.slug[0]}</p>}<label>Prix (DH)<input disabled={locked} required type="number" min={1} max={1_000_000} value={value.priceDh} onChange={e=>setValue({...value,priceDh:Number(e.target.value)})}/></label><label>Description<textarea disabled={locked} required minLength={20} maxLength={3000} rows={8} value={value.description} onChange={e=>setValue({...value,description:e.target.value})}/></label><label><input disabled={locked||(!value.isVisible&&!canPublish)} type="checkbox" checked={value.isVisible} onChange={e=>setValue({...value,isVisible:e.target.checked})}/> Produit visible</label>{!canPublish&&<p>Ajoutez une image et une déclinaison pour publier. Le brouillon reste enregistrable.</p>}<section><h2>Images</h2><label className="secondary-link">{uploading?"Téléversement…":"Téléverser une image"}<input className="sr-only" disabled={locked||value.images.length>=10} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>void upload(e.target.files?.[0])}/></label>{value.images.map((image,index)=><div className="admin-image-row" key={image.id??image.url}><a href={image.url} target="_blank" rel="noreferrer">Aperçu {index+1}</a><label>Texte alternatif<input disabled={locked} required minLength={2} maxLength={160} value={image.alt} onChange={e=>setValue({...value,images:value.images.map((item,current)=>current===index?{...item,alt:e.target.value}:item)})}/></label><button disabled={locked||index===0} type="button" onClick={()=>move(index,-1)}>Monter</button><button disabled={locked||index===value.images.length-1} type="button" onClick={()=>move(index,1)}>Descendre</button><button disabled={locked} type="button" onClick={()=>setValue({...value,images:value.images.filter((_,current)=>current!==index).map((item,position)=>({...item,position}))})}>Retirer</button></div>)}</section><VariantEditor value={value.variants} onChange={variants=>setValue({...value,variants})} disabled={locked}/><button className="admin-submit" disabled={locked}>{busy?"Enregistrement…":"Enregistrer"}</button></form> }
